export const GET_WALLETS_START = 'GET_WALLETS_START';
export const GET_WALLETS_SUCCESS = 'GET_WALLETS_SUCCESS';
export const GET_WALLETS_ERROR = 'GET_WALLETS_ERROR';

export const GET_WALLET_OPERATIONS_START = 'GET_WALLET_OPERATIONS_START';
export const GET_WALLET_OPERATIONS_SUCCESS = 'GET_WALLET_OPERATIONS_SUCCESS';
export const GET_WALLET_OPERATIONS_ERROR = 'GET_WALLET_OPERATIONS_ERROR';

export const ADD_OPERATION_START = 'ADD_OPERATION_START';
export const ADD_OPERATION_SUCCESS = 'ADD_OPERATION_SUCCESS';
export const ADD_OPERATION_ERROR = 'ADD_OPERATION_ERROR';