export const GET_PERSONAL_CATEGORIES_START = 'GET_PERSONAL_CATEGORIES_START';
export const GET_PERSONAL_CATEGORIES_SUCCESS = 'GET_PERSONAL_CATEGORIES_SUCCESS';
export const GET_PERSONAL_CATEGORIES_ERROR = 'GET_PERSONAL_CATEGORIES_ERROR';

export const GET_WALLET_CATEGORIES_START = 'GET_WALLET_CATEGORIES_START';
export const GET_WALLET_CATEGORIES_SUCCESS = 'GET_WALLET_CATEGORIES_SUCCESS';
export const GET_WALLET_CATEGORIES_ERROR = 'GET_WALLET_CATEGORIES_ERROR';

export const ADD_CATEGORY_START = 'ADD_CATEGORY_START';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_ERROR = 'ADD_CATEGORY_ERROR';
