export const GET_NOTIFICATIONS_START = 'GET_NOTIFICATIONS_START';
export const GET_NOTIFICATIONS_SUCCESS = 'GET_NOTIFICATIONS_SUCCESS';
export const GET_NOTIFICATIONS_ERROR = 'GET_NOTIFICATIONS_ERROR';

export const ACCEPT_INVITATION_START = 'ACCEPT_INVITATION_START';
export const ACCEPT_INVITATION_SUCCESS = 'ACCEPT_INVITATION_SUCCESS';
export const ACCEPT_INVITATION_ERROR = 'ACCEPT_INVITATION_ERROR';

export const CANCEL_INVITATION_START = 'CANCEL_INVITATION_START';
export const CANCEL_INVITATION_SUCCESS = 'CANCEL_INVITATION_SUCCESS';
export const CANCEL_INVITATION_ERROR = 'CANCEL_INVITATION_ERROR';
